<?php

namespace Test\AbraFlexi\Processor\Plugins;

use AbraFlexi\Processor\Plugins\Banka;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-06-21 at 09:48:26.
 */
class BankaTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Banka
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Banka();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Processor\Plugins\Banka::create
     * @todo   Implement testcreate().
     */
    public function testcreate() {
        $this->assertEquals('', $this->object->create());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
