<?php

namespace Test\AbraFlexi\Processor\Plugins;

use AbraFlexi\Processor\Plugins\FakturaPrijata;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-06-21 at 09:48:27.
 */
class FakturaPrijataTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var FakturaPrijata
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new FakturaPrijata();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Processor\Plugins\FakturaPrijata::create
     * @todo   Implement testcreate().
     */
    public function testcreate() {
        $this->assertEquals('', $this->object->create());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Processor\Plugins\FakturaPrijata::bankOrderSent
     * @todo   Implement testbankOrderSent().
     */
    public function testbankOrderSent() {
        $this->assertEquals('', $this->object->bankOrderSent());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Processor\Plugins\FakturaPrijata::loadOrderData
     * @todo   Implement testloadOrderData().
     */
    public function testloadOrderData() {
        $this->assertEquals('', $this->object->loadOrderData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
