<?php

namespace Test\AbraFlexi\Processor\Plugins;

use AbraFlexi\Processor\Plugins\Kontakt;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-06-21 at 09:48:26.
 */
class KontaktTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Kontakt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Kontakt();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

}
