<?php

namespace Test\AbraFlexi\Processor;

use AbraFlexi\Processor\Api;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-06-21 at 09:48:24.
 */
class ApiTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Api
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Api();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Processor\Api::logRequest
     * @todo   Implement testlogRequest().
     */
    public function testlogRequest() {
        $this->assertEquals('', $this->object->logRequest());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Processor\Api::logResponse
     * @todo   Implement testlogResponse().
     */
    public function testlogResponse() {
        $this->assertEquals('', $this->object->logResponse());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Processor\Api::addStatusMessage
     * @todo   Implement testaddStatusMessage().
     */
    public function testaddStatusMessage() {
        $this->assertEquals('', $this->object->addStatusMessage());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Processor\Api::getStatusMessages
     * @todo   Implement testgetStatusMessages().
     */
    public function testgetStatusMessages() {
        $this->assertEquals('', $this->object->getStatusMessages());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Processor\Api::cleanSatatusMessages
     * @todo   Implement testcleanSatatusMessages().
     */
    public function testcleanSatatusMessages() {
        $this->assertEquals('', $this->object->cleanSatatusMessages());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Processor\Api::getLogger
     * @todo   Implement testgetLogger().
     */
    public function testgetLogger() {
        $this->assertEquals('', $this->object->getLogger());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Processor\Api::logBanner
     * @todo   Implement testlogBanner().
     */
    public function testlogBanner() {
        $this->assertEquals('', $this->object->logBanner());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
