<?php

namespace Test\AbraFlexi\Processor;

use AbraFlexi\Processor\WebHooker;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-06-21 at 09:48:24.
 */
class WebHookerTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var WebHooker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new WebHooker();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Processor\WebHooker::getChanges
     * @todo   Implement testgetChanges().
     */
    public function testgetChanges() {
        $this->assertEquals('', $this->object->getChanges());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
