#!/bin/sh
set -e

. /usr/share/debconf/confmodule

composer-debian abraflexi-changes-processor

if [ -f /usr/share/dbconfig-common/dpkg/postinst ]; then
    . /usr/share/dbconfig-common/dpkg/postinst
    dbc_generate_include_args="-U -o template_infile=/usr/lib/abraflexi-changes-processor/.env.template"
    dbc_generate_include=template:/etc/abraflexi-changes-processor/.env
    dbc_generate_include_owner="root:www-data"
    dbc_generate_include_perms="664"
    dbc_dbfile_owner="www-data:www-data"
    dbc_dbfile_perms="0664"
    dbc_dbuser=changesprocessor
    dbc_dbname=changesprocessor

    dbc_go abraflexi-changes-processor "$@" || true

#    echo "Pre-DependsDbconfig Common configuration: /etc/dbconfig-common/abraflexi-changes-processor.conf"
#    cat /etc/dbconfig-common/abraflexi-changes-processor.conf
#    echo "Configuration Used: /etc/abraflexi-changes-processor/.env"
#    cat /etc/abraflexi-changes-processor/.env
#    echo "Phinx Adapter: /usr/lib/abraflexi-changes-processor/phinx-adapter.php"
#    cat /usr/lib/abraflexi-changes-processor/phinx-adapter.php


    phinx migrate -c /usr/lib/abraflexi-changes-processor/phinx-adapter.php

#    if [ -f /var/lib/abraflexi-changes-processor/changesprocessor ] ; then
#        chown root:www-data /var/lib/abraflexi-changes-processor/
#        chmod ug+rw /var/lib/abraflexi-changes-processor/
#        chown root:www-data /var/lib/abraflexi-changes-processor/changesprocessor
#        chmod ug+rw /var/lib/abraflexi-changes-processor/changesprocessor
#    fi

fi


case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
